THF-524: add redirect to translation not exists, lang code and field …
City-of-Helsinki/employment-services-ui pull request #321
Opened 2023-05-31 08:03 UTC by MariaHokas

- Added field `field_content_language` and used it for creating lang html attribute value.
- When content doesn't have translation Next will create link to the the local front page. Previously next created link based on the original link even the link didn't exist.

How to test:

- Create basic page and give the page different Content language compared to Language.
- See that you can see lang link on article HTML-tag
- Create new basic page with any language. Don't create translations.
- Try to get to the page's other translation example english
- You should end up to front page for the language you tried to see the page. This case http://localhost:3000/en

2023-05-31 08:04 UTC, MariaHokas commented on src/components/pageTemplates/NodeBasicPage.tsx
> +      : langcode;
Actual change

2023-05-31 08:05 UTC, MariaHokas commented on src/components/pageTemplates/NodeBasicPage.tsx
> +    <article lang={langAttribute}>
Real change

2023-06-06 06:33 UTC, juho-lehmonen requested changes
The field_content_language related changes should be removed because the field was removed from Drupal too.

2023-06-06 06:33 UTC, juho-lehmonen commented on src/components/pageTemplates/NodeBasicPage.tsx
> +    field_content_language?.resourceIdObjMeta.drupal_internal__target_id;
This field has been removed because we ended up not needing the funtionality after all, so it should be removed from there too.

2023-07-04 05:44 UTC, closed without merging